version: '3'

services:
  greenmail:
    image: "greenmail/standalone"
    environment:
      - JAVA_OPTS=-Dgreenmail.verbose -Dgreenmail.users=foo:password@example.com
    ports:
      - 3025:3025 # SMTP
      - 3110:3110 # POP3
      - 3143:3143 # IMAP
      - 3465:3465 # SMTPS
      - 3993:3993 # IMAPS
      - 3995:3995 # POP3S
    networks:
      - greenmail-net

  roundcube:
    image: roundcube/roundcubemail
    depends_on:
      - greenmail
    ports:
      - 8000:80
      - 9000:9000
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=greenmail  # IMAP server - tls:// prefix for STARTTLS
      - ROUNDCUBEMAIL_DEFAULT_PORT=3143       # IMAP port
      - ROUNDCUBEMAIL_SMTP_SERVER=greenmail   # SMTP server - tls:// prefix for STARTTLS
      - ROUNDCUBEMAIL_SMTP_PORT=3025          # SMTP port
    networks:
      - greenmail-net

networks:
  greenmail-net:
